using System.Collections.Generic;
using System.Runtime.InteropServices.WindowsRuntime;
using UnityEngine;

public class AStarManager : MonoBehaviour
{
    // AStarManager static instance of map to be referenced in other parts of program 
    public static AStarManager instance;

    private void Awake()
    {
        // initialize the instance of AStarManager when game starts
        instance = this;
    }


    // this method will create a path from where enemy is to enemy's target (tower)
    public List<Node> GeneratePath(Node start, Node end)
    {
        // this will keep track of the current potential nodes that are being considered as parts of the path
        List<Node> openSet = new List<Node>();
        // this will keep track of the node with the lowestF score
        int lowestF = 0;
        // this will hold the selected lowest node
        Node currentNode;
        // this will hold the path from start node to end node
        List<Node> path = new List<Node>();

        // initialize all nodes in the scene to have the max gScore value
        foreach(Node n in FindObjectsByType<Node>(FindObjectsSortMode.None))
        {
            n.gScore = float.MaxValue;
        }

        // initialize the gScore of starting point
        start.gScore = 0;
        // initialize the hScore from essentially the distance between start and end
        start.hScore = Vector2.Distance(start.transform.position, end.transform.position);
        //add the starting node to the set of nodes we are looking at
        openSet.Add(start);

        // while there are nodes still to traverse to (forever)
        while(openSet.Count > 0)
        {
            // find the node with the lowest f score in the openSet list
            for(int i =1; i < openSet.Count; i++)
            {
                // if node is less than the current lowestF node then replace it
                if(openSet[i].FScore() < openSet[lowestF].FScore())
                {
                    lowestF = i;
                }   
            }

            // pick the lowest node/traverse to it
            currentNode = openSet[lowestF];
            // then remove it from the set of nodes we are currently looking at
            openSet.Remove(currentNode);

            // if we end up reaching the target
            if(currentNode == end)
            {   
                // path is generated by backtracking in which we first insert end node
                path.Insert(0, end);
                
                // backtrack until we reach the start
                while(currentNode != start)
                {
                    // basically start to traverse the tree backwards
                    currentNode = currentNode.fromNode;
                    // and builds path while doing so
                    path.Add(currentNode);
                }
                // to make the list start from starting node and end at end node
                path.Reverse();
                return path;
            }

            // this is to check and update the neighboring nodes gScore and hScore values of the current node
            foreach(Node neighborNode in currentNode.neighbors)
            {
                // basically currentNode's g score + the distance from current node to current neighbor node
                float calculatedGScore = currentNode.gScore + Vector2.Distance(currentNode.transform.position, neighborNode.transform.position);

                // if there is a new optimal path than our current "optimal" path going from any "currentNode" to neighbor
                if(calculatedGScore < neighborNode.gScore)
                {
                    // the most optimal node to backtrack to would be the currentNode
                    neighborNode.fromNode = currentNode;
                    // the current neighborNode's g score is then updated with our "new" optimal g score 
                    neighborNode.gScore = calculatedGScore;
                    // the current neighborNode's h score is updated with the cost from the current neighbor node to the end/target 
                    neighborNode.hScore = Vector2.Distance(neighborNode.transform.position, end.transform.position);

                    // if the neighbor node isn't already being considered, then consider it
                    if(!openSet.Contains(neighborNode))
                    {
                        openSet.Add(neighborNode);
                    }
                }
                 
            }
        }

        // basically just means that there is no path between start and end node
        return null;
    }
}
